[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
wetawelu_contract = "GkgdVw7gRnR28Q979EQPiriovTrXBmpJSZLRWXQuG2EM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\kodesage\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
