[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
wetawelu_solanacontract = "Dtg6jj2BmZTaUY3JSDDZe91Vx7X6EKNCJx8b4ZH8gUdP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\kodesage\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
